# task_manager/api/schemas.py
from task_manager.domain.models import Status, Priority, Task, History, HistoryType
from pydantic import BaseModel, Field
from datetime import datetime
from dataclasses import asdict
from typing import Optional, Type, TYPE_CHECKING

if TYPE_CHECKING:
    pass


class TaskRequestPayload(BaseModel):
    """Schema for creating a new task.
    
    Only description is required. Other fields have sensible defaults:
    - deadline: Optional - can be blank for general tasks
    - status: Defaults to TODO
    - priority: Defaults to LOW
    - id: Auto-generated if not provided
    """
    description: str = Field(..., min_length=1)  # Required, non-empty
    deadline: Optional[datetime] = None  # Optional - None means general task
    # Note: status and priority use enum default values for defaults
    status: Status = Status.TODO
    priority: Priority = Priority.LOW

    model_config = {
        "use_enum_values": True
    }

    def to_domain_model(self) -> Task:
        """Convert request payload to domain model."""
        return Task(
            id=None,  # ID will be generated by service
            description=self.description,
            deadline=self.deadline,  # Can be None for general tasks
            status=Status(self.status),
            priority=Priority(self.priority)
        )


class TaskResponsePayload(BaseModel):
    """Schema for task responses.
    
    Contains all task fields including:
    - id: The unique identifier
    - description: Task description
    - deadline: Due date (required in response - serialized from optional field)
    - status: Current status
    - priority: Priority level
    """
    id: str
    description: str
    deadline: Optional[datetime]  # Can be None for general tasks
    status: Status
    priority: Priority

    model_config = {
        "use_enum_values": True
    }

    @classmethod
    def from_domain_model(cls, task: Task)-> "TaskResponsePayload":
        """Convert domain model to response payload."""
        return cls(**asdict(task))


# Backwards compatibility - TaskPayload now refers to TaskResponsePayload
# This allows existing code using TaskPayload to continue working
TaskPayload = TaskResponsePayload


class UpdateTaskRequestPayload(BaseModel):
    """Schema for updating an existing task.
    
    All fields are optional to allow partial updates:
    - description: Task description (can be updated)
    - deadline: Due date (can be updated, set to None to remove deadline)
    - status: Current status (can be updated)
    - priority: Priority level (can be updated)
    """
    description: Optional[str] = Field(None, min_length=1)
    deadline: Optional[datetime] = None
    status: Optional[Status] = None
    priority: Optional[Priority] = None

    model_config = {
        "use_enum_values": True
    }

    def to_domain_model(self, existing_task: Task) -> Task:
        """Convert request payload to domain model, preserving existing values for None fields."""
        return Task(
            id=existing_task.id,
            description=self.description if self.description is not None else existing_task.description,
            deadline=self.deadline if self.deadline is not None else existing_task.deadline,
            status=Status(self.status) if self.status is not None else existing_task.status,
            priority=Priority(self.priority) if self.priority is not None else existing_task.priority
        )


class HistoryResponsePayload(BaseModel):
    """Schema for history responses.
    
    Contains all history fields including:
    - id: The unique identifier
    - entity_id: ID of the task or subtask
    - entity_type: "task" or "subtask"
    - change_type: What happened (created, updated, deleted)
    - timestamp: When the change occurred
    - old_value: Previous state (JSON string)
    - new_value: New state (JSON string)
    """
    id: str
    entity_id: str
    entity_type: str
    change_type: HistoryType
    timestamp: datetime
    old_value: Optional[str]
    new_value: Optional[str]

    model_config = {
        "use_enum_values": True
    }

    @classmethod
    def from_domain_model(cls, history: History) -> "HistoryResponsePayload":
        """Convert domain model to response payload."""
        return cls(**asdict(history))

