# task_manager/api/schemas.py
from task_manager.domain.models import Status, Priority, Task
from pydantic import BaseModel, Field
from datetime import datetime
from dataclasses import asdict
from typing import Optional, Type, TYPE_CHECKING

if TYPE_CHECKING:
    pass


class TaskRequestPayload(BaseModel):
    """Schema for creating a new task.
    
    Only description is required. Other fields have sensible defaults:
    - deadline: Optional - can be blank for general tasks
    - status: Defaults to TODO
    - priority: Defaults to LOW
    - id: Auto-generated if not provided
    """
    description: str = Field(..., min_length=1)  # Required, non-empty
    deadline: Optional[datetime] = None  # Optional - None means general task
    # Note: status and priority use enum default values for defaults
    status: Status = Status.TODO
    priority: Priority = Priority.LOW

    model_config = {
        "use_enum_values": True
    }

    def to_domain_model(self) -> Task:
        """Convert request payload to domain model."""
        return Task(
            id=None,  # ID will be generated by service
            description=self.description,
            deadline=self.deadline,  # Can be None for general tasks
            status=Status(self.status),
            priority=Priority(self.priority)
        )


class TaskResponsePayload(BaseModel):
    """Schema for task responses.
    
    Contains all task fields including:
    - id: The unique identifier
    - description: Task description
    - deadline: Due date (required in response - serialized from optional field)
    - status: Current status
    - priority: Priority level
    """
    id: str
    description: str
    deadline: Optional[datetime]  # Can be None for general tasks
    status: Status
    priority: Priority

    model_config = {
        "use_enum_values": True
    }

    @classmethod
    def from_domain_model(cls, task: Task)-> "TaskResponsePayload":
        """Convert domain model to response payload."""
        return cls(**asdict(task))


# Backwards compatibility - TaskPayload now refers to TaskResponsePayload
# This allows existing code using TaskPayload to continue working
TaskPayload = TaskResponsePayload

